name: Maven

on:
  push:
    branches: [ feature/* ]


  workflow_dispatch:

jobs:
    build:
      runs-on: maven:3.9.7

      steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - run: git checkout HEAD^